### ISSUE TITLE
메롱인가

### ISSUE THREAD

**Issue by nyong0607** [khc1201/RoomEscape#54]
- [x] 이것이 메롱이 맞는가?
- [x] 어플에서도 메롱인가?? 하투인가??♡

@khc1201

**Comment by khc1201** [comment]
@nyong0607 하투입니다! 꺄르르륵

**Comment by khc1201** [comment]
![image](https://user-images.githubusercontent.com/41064972/82225846-adcc9f00-9960-11ea-9ad5-24cdf695d228.png)

1번 : 이 글을 누구에게 할당할 것인지 나오고!
2번 : 이것은 무슨 일인가! bug 인가! work 인가! 여러개 고를 수도 있지롱 꺄륵
3번 : 어느 프로젝트에 할당 할 것인가!
(Issue 말고 옆옆옆에 보면 Project 라고 이써! 툐리의 베타 버전을 위해 이슈들을 모아놓은 곳이지!)
4번 : 마일스톤은 언제까지인가! 이 일을 언제까지하면 대는가!

**Comment by nyong0607** [comment]
완-성-!

**Comment by nyong0607** [comment]
이러면 알람이 가나유?
